In [1]:
import pandas as pd

data = pd.read_csv("data.csv")
data.head(2)

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SF1AA2CA,2016.06,1116.386,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
1,BDCQ.SF1AA2CA,2016.09,1070.874,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN

In [5]:
data.describe()

            Period    Data_value  Magnitude  Series_title_5
count  9555.000000   9510.000000     9555.0             0.0
mean   2020.845501   5515.748286        6.0             NaN
std       2.892394   8065.792799        0.0             NaN
min    2016.060000   -398.194000        6.0             NaN
25%    2018.120000    734.175250        6.0             NaN
50%    2021.060000   2374.097000        6.0             NaN
75%    2023.120000   5257.780750        6.0             NaN
max    2026.030000  43002.425000        6.0             NaN

In [6]:
data_value = data['Data_value']
data_value

0       1116.386
1       1070.874
2       1054.408
3       1010.665
4       1233.700
          ...
9550     699.681
9551     587.843
9552     658.866
9553     734.757
9554     884.011
Name: Data_value, Length: 9555, dtype: float64

In [7]:
data_value.mean()

np.float64(5515.748285804416)

In [9]:
data_value.mode()

0    5613.637
1    6569.408
2    7057.335
3    7214.922
4    7584.800
5    7654.068
6    8093.100
7    8133.305
8    8521.457
9    9319.980
Name: Data_value, dtype: float64

In [10]:
data_value.median()

np.float64(2374.0969999999998)

In [13]:
data_value.count()

np.int64(9510)

In [15]:
# Quartiles 🍕 split your sorted dataset into four equal parts(25% of the data each)
# :Q1 (First Quartile / 25th Percentile): The middle number between the smallest value and the median.
# Q2 (Second Quartile / 50th Percentile): The median of the dataset.
# Q3 (Third Quartile / 75th Percentile): The middle number between the median and the largest value.

# IQR (Interquartile Range) 📏 is the distance between the third and first quartiles:
# IQR = Q3 - Q1

Q1 = data_value.quantile(0.25)
Q2 = data_value.quantile(0.50)
Q3 = data_value.quantile(0.75)

print(Q1, ":", Q2, ":", Q3)

734.17525 : 2374.0969999999998 : 5257.78075

In [ ]:
# The Interquartile Range (IQR)

IQR = Q3 - Q1
IQR

np.float64(4523.6055)