In [1]:
import pandas as pd

data = pd.read_csv("data.csv")
print(data.head(5))

  Series_reference   Period  Data_value Suppressed STATUS    UNITS  Magnitude  \
0    BDCQ.SF1AA2CA  2016.06    1116.386        NaN      F  Dollars          6
1    BDCQ.SF1AA2CA  2016.09    1070.874        NaN      F  Dollars          6
2    BDCQ.SF1AA2CA  2016.12    1054.408        NaN      F  Dollars          6
3    BDCQ.SF1AA2CA  2017.03    1010.665        NaN      F  Dollars          6
4    BDCQ.SF1AA2CA  2017.06    1233.700        NaN      F  Dollars          6

                          Subject  \
0  Business Data Collection - BDC
1  Business Data Collection - BDC
2  Business Data Collection - BDC
3  Business Data Collection - BDC
4  Business Data Collection - BDC

                                             Group            Series_title_1  \
0  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)
1  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)
2  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)
3  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)
4  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)

         Series_title_2  Series_title_3 Series_title_4  Series_title_5
0  Forestry and Logging  Current prices     Unadjusted             NaN
1  Forestry and Logging  Current prices     Unadjusted             NaN
2  Forestry and Logging  Current prices     Unadjusted             NaN
3  Forestry and Logging  Current prices     Unadjusted             NaN
4  Forestry and Logging  Current prices     Unadjusted             NaN

In [2]:
print(data.tail(2))

     Series_reference   Period  Data_value Suppressed STATUS    UNITS  \
9553     BDCQ.SF8RSCA  2025.12     734.757        NaN      F  Dollars
9554     BDCQ.SF8RSCA  2026.03     884.011        NaN      F  Dollars

      Magnitude                         Subject  \
9553          6  Business Data Collection - BDC
9554          6  Business Data Collection - BDC

                                                Group    Series_title_1  \
9553  Industry by financial variable (NZSIOC Level 1)  Operating profit
9554  Industry by financial variable (NZSIOC Level 1)  Operating profit

                           Series_title_2 Series_title_3 Series_title_4  \
9553  Arts, Recreation and Other Services        Current     Unadjusted
9554  Arts, Recreation and Other Services        Current     Unadjusted

      Series_title_5
9553             NaN
9554             NaN

In [ ]:
# shape returns the (rows and column)
data.shape

(9555, 14)

In [ ]:
# column returns column names
data.columns

Index(['Series_reference', 'Period', 'Data_value', 'Suppressed', 'STATUS',
       'UNITS', 'Magnitude', 'Subject', 'Group', 'Series_title_1',
       'Series_title_2', 'Series_title_3', 'Series_title_4', 'Series_title_5'],
      dtype='str')

In [ ]:
# returns all columns name and thier info
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9555 entries, 0 to 9554
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  9555 non-null   str
 1   Period            9555 non-null   float64
 2   Data_value        9510 non-null   float64
 3   Suppressed        15 non-null     str
 4   STATUS            9555 non-null   str
 5   UNITS             9555 non-null   str
 6   Magnitude         9555 non-null   int64
 7   Subject           9555 non-null   str
 8   Group             9555 non-null   str
 9   Series_title_1    9555 non-null   str
 10  Series_title_2    9555 non-null   str
 11  Series_title_3    9555 non-null   str
 12  Series_title_4    9555 non-null   str
 13  Series_title_5    0 non-null      float64
dtypes: float64(3), int64(1), str(10)
memory usage: 1.0 MB

In [ ]:
# describe retuens basic info like mean, max and only works on numerical values
data.describe()

            Period    Data_value  Magnitude  Series_title_5
count  9555.000000   9510.000000     9555.0             0.0
mean   2020.845501   5515.748286        6.0             NaN
std       2.892394   8065.792799        0.0             NaN
min    2016.060000   -398.194000        6.0             NaN
25%    2018.120000    734.175250        6.0             NaN
50%    2021.060000   2374.097000        6.0             NaN
75%    2023.120000   5257.780750        6.0             NaN
max    2026.030000  43002.425000        6.0             NaN

In [10]:
data.isnull()

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,False,False,False,True,False,False,False,False,False,False,False,False,False,True
1,False,False,False,True,False,False,False,False,False,False,False,False,False,True
2,False,False,False,True,False,False,False,False,False,False,False,False,False,True
3,False,False,False,True,False,False,False,False,False,False,False,False,False,True
4,False,False,False,True,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9550,False,False,False,True,False,False,False,False,False,False,False,False,False,True
9551,False,False,False,True,False,False,False,False,False,False,False,False,False,True
9552,False,False,False,True,False,False,False,False,False,False,False,False,False,True
9553,False,False,False,True,False,False,False,False,False,False,False,False,False,True
9554,False,False,False,True,False,False,False,False,False,False,False,False,False,True

In [11]:
data.isnull().sum()

Series_reference       0
Period                 0
Data_value            45
Suppressed          9540
STATUS                 0
UNITS                  0
Magnitude              0
Subject                0
Group                  0
Series_title_1         0
Series_title_2         0
Series_title_3         0
Series_title_4         0
Series_title_5      9555
dtype: int64